version: '3.1'
services:
  app:
    container_name: emp-postgres
    image: emp-mgmt-service
    build: ./
    ports:
      - "8081:8080"
      - "5432:5433"
    depends_on:
      - postgresqldb
  postgresqldb:
    image: postgres
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=employees